# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'RxSwiftPlayground' do
  use_frameworks!

  pod 'RxSwift', '~> 4.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
